### PR TITLE
Scatter plot implementation for bokeh

### PR DESCRIPTION
**Pull request by chetnawarade**
Two dimensional bokeh scatter plot for pixiedust.

### CODE REVIEW

**Comment by DTAIEB** [comment]
@chetnawarade : implementation looks good, but you have a reference to histogramDisplay in the __init.py file but the file doesn't exist in the branch.

**Comment by chetnawarade** [comment]
Correct histogramDisplay is leftover. histogramDisplay.py is local to my branch and not ready.

**Comment by chetnawarade** [comment]
removed `from .histogramDisplay import *` line from __init__.py, committed to plotting-tools branch. If build passes, I will try to update/merge with this PR or open new. New to github, still learning nuances.

**Comment by chetnawarade** [comment]
Looks like merging PR should bring in removal of line `from .histogramDisplay import *` in __init__.py to your branch @DTAIEB.

**Pull request merged**
